export const GET_REQUEST_DATA_FACE = "GET_REQUEST_DATA_FACE";
export const GET_FAILURE_DATA_FACE = "GET_FAILURE_DATA_FACE";
export const GET_SUCCESS_DATA_FACE = "GET_SUCCESS_DATA_FACE";

export const GET_REQUEST_DATA_SKIN = "GET_REQUEST_DATA_SKIN";
export const GET_FAILURE_DATA_SKIN = "GET_FAILURE_DATA_SKIN";
export const GET_SUCCESS_DATA_SKIN = "GET_SUCCESS_DATA_SKIN";




